### ISSUE TITLE
Cannot read properties of undefined (reading 'lastPage')

### ISSUE THREAD

**Issue by sethzindler** [philnash/astro-pagination#2]
Getting the following error when using the default options of the component:

```
Cannot read properties of undefined (reading 'lastPage')
```

My code (unformatted):

```astro
--- 
import { getCollection, CollectionEntry } from "astro:content"
import Pagination from "@philnash/astro-pagination"
type Props = { page: Page<CollectionEntry<"recipes">> }
const { page } = Astro.props 
---

<Pagination
  page={page}
  urlPattern={"/recipes/page/{}"}
  firstPageUrl="/recipes"
  windowSize={3}
  showPrevNext={true}
/>
```

Any help would be greatly appreciated.

**Comment by philnash** [comment]
It looks to me like you aren't passing a `page` object to the component with the code you're showing. You're using a custom `firstPageUrl`. Is that first page served by the same Astro page? In my own blog, the first page and the remaining pages are served by different Astro pages in order to get the URLs to work. So on my first page I have to construct a page object and then pass it to the component that renders the list.

Check out the implementation of [the first page](https://github.com/philnash/philna.sh/blob/main/src/pages/blog/index.astro) and [the remaining pages](https://github.com/philnash/philna.sh/blob/main/src/pages/blog/%5Byear%5D/%5Bmonth%5D/%5Bday%5D/%5B...slug%5D.astro).

**Comment by sethzindler** [comment]
> It looks to me like you aren't passing a `page` object to the component with the code you're showing. You're using a custom `firstPageUrl`. Is that first page served by the same Astro page? In my own blog, the first page and the remaining pages are served by different Astro pages in order to get the URLs to work. So on my first page I have to construct a page object and then pass it to the component that renders the list.
> 
> Check out the implementation of [the first page](https://github.com/philnash/philna.sh/blob/main/src/pages/blog/index.astro) and [the remaining pages](https://github.com/philnash/philna.sh/blob/main/src/pages/blog/%5Byear%5D/%5Bmonth%5D/%5Bday%5D/%5B...slug%5D.astro).

I figured it out. Thanks for the reply!

**Comment by philnash** [comment]
Glad to hear it! Let me know if there's any other feedback! (I... err... have my email notifications on now after realising I'd turned them off before)
